name: Documentation

on:
  push:
    branches:
      - main
      - develop
    tags: '*'
  pull_request:

# sphinx-build doc _build
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          # pip install -r docs/requirements.txt
          pip install -e .[docs]
      - name: Sphinx build
        run: |
          cd docs
          make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          # publish_dir: _build/
          # force_orphan: true
